#ifndef CONSTANTS_H
#define CONSTANTS_H

#define WINDOW_WIDTH  800
#define WINDOW_HEIGHT 600
#define PLAYERWIDTH 50
#define PLAYERHEIGHT 50
#define PLAYERSPEED 200

// used for projectile.c
#define PROJECTILE_VELOCITY_INIT 50
#define PROJECTILE_WIDTH 100
#define PROJECTILE_HEIGHT 100
#define PROJECTILE_ANGLE_RIGHT 0
#define PROJECTILE_ANGLE_UP 90
#define PROJECTILE_ANGLE_LEFT 180
#define PROJECTILE_ANGLE_DOWN 270

#endif 
