#ifndef CONSTANTS_H
#define CONSTANTS_H

#define WINDOW_WIDTH  800
#define WINDOW_HEIGHT 600
#define PLAYERWIDTH 70
#define PLAYERHEIGHT 70
#define PLAYERSPEED 200
#define WORLD_WIDTH 1600
#define WORLD_HEIGHT 1200

#endif 
